/* Lista completa dos livros da Bíblia com nome, abreviação, testamento e nº de capítulos */
export const LIVROS_BIBLIA = [
  // ── Antigo Testamento ──
  { nome: "Gênesis",          abrev: "gn",   testamento: "AT", capitulos: 50 },
  { nome: "Êxodo",            abrev: "ex",   testamento: "AT", capitulos: 40 },
  { nome: "Levítico",         abrev: "lv",   testamento: "AT", capitulos: 27 },
  { nome: "Números",          abrev: "nm",   testamento: "AT", capitulos: 36 },
  { nome: "Deuteronômio",     abrev: "dt",   testamento: "AT", capitulos: 34 },
  { nome: "Josué",            abrev: "js",   testamento: "AT", capitulos: 24 },
  { nome: "Juízes",           abrev: "jz",   testamento: "AT", capitulos: 21 },
  { nome: "Rute",             abrev: "rt",   testamento: "AT", capitulos: 4  },
  { nome: "1 Samuel",         abrev: "1sm",  testamento: "AT", capitulos: 31 },
  { nome: "2 Samuel",         abrev: "2sm",  testamento: "AT", capitulos: 24 },
  { nome: "1 Reis",           abrev: "1rs",  testamento: "AT", capitulos: 22 },
  { nome: "2 Reis",           abrev: "2rs",  testamento: "AT", capitulos: 25 },
  { nome: "1 Crônicas",       abrev: "1cr",  testamento: "AT", capitulos: 29 },
  { nome: "2 Crônicas",       abrev: "2cr",  testamento: "AT", capitulos: 36 },
  { nome: "Esdras",           abrev: "ed",   testamento: "AT", capitulos: 10 },
  { nome: "Neemias",          abrev: "ne",   testamento: "AT", capitulos: 13 },
  { nome: "Ester",            abrev: "et",   testamento: "AT", capitulos: 10 },
  { nome: "Jó",               abrev: "jo",   testamento: "AT", capitulos: 42 },
  { nome: "Salmos",           abrev: "sl",   testamento: "AT", capitulos: 150},
  { nome: "Provérbios",       abrev: "pv",   testamento: "AT", capitulos: 31 },
  { nome: "Eclesiastes",      abrev: "ec",   testamento: "AT", capitulos: 12 },
  { nome: "Cantares",         abrev: "ct",   testamento: "AT", capitulos: 8  },
  { nome: "Isaías",           abrev: "is",   testamento: "AT", capitulos: 66 },
  { nome: "Jeremias",         abrev: "jr",   testamento: "AT", capitulos: 52 },
  { nome: "Lamentações",      abrev: "lm",   testamento: "AT", capitulos: 5  },
  { nome: "Ezequiel",         abrev: "ez",   testamento: "AT", capitulos: 48 },
  { nome: "Daniel",           abrev: "dn",   testamento: "AT", capitulos: 12 },
  { nome: "Oséias",           abrev: "os",   testamento: "AT", capitulos: 14 },
  { nome: "Joel",             abrev: "jl",   testamento: "AT", capitulos: 3  },
  { nome: "Amós",             abrev: "am",   testamento: "AT", capitulos: 9  },
  { nome: "Obadias",          abrev: "ob",   testamento: "AT", capitulos: 1  },
  { nome: "Jonas",            abrev: "jn",   testamento: "AT", capitulos: 4  },
  { nome: "Miquéias",         abrev: "mq",   testamento: "AT", capitulos: 7  },
  { nome: "Naum",             abrev: "na",   testamento: "AT", capitulos: 3  },
  { nome: "Habacuque",        abrev: "hc",   testamento: "AT", capitulos: 3  },
  { nome: "Sofonias",         abrev: "sf",   testamento: "AT", capitulos: 3  },
  { nome: "Ageu",             abrev: "ag",   testamento: "AT", capitulos: 2  },
  { nome: "Zacarias",         abrev: "zc",   testamento: "AT", capitulos: 14 },
  { nome: "Malaquias",        abrev: "ml",   testamento: "AT", capitulos: 4  },

  // ── Novo Testamento ──
  { nome: "Mateus",           abrev: "mt",   testamento: "NT", capitulos: 28 },
  { nome: "Marcos",           abrev: "mc",   testamento: "NT", capitulos: 16 },
  { nome: "Lucas",            abrev: "lc",   testamento: "NT", capitulos: 24 },
  { nome: "João",             abrev: "jo",   testamento: "NT", capitulos: 21 },
  { nome: "Atos",             abrev: "at",   testamento: "NT", capitulos: 28 },
  { nome: "Romanos",          abrev: "rm",   testamento: "NT", capitulos: 16 },
  { nome: "1 Coríntios",      abrev: "1co",  testamento: "NT", capitulos: 16 },
  { nome: "2 Coríntios",      abrev: "2co",  testamento: "NT", capitulos: 13 },
  { nome: "Gálatas",          abrev: "gl",   testamento: "NT", capitulos: 6  },
  { nome: "Efésios",          abrev: "ef",   testamento: "NT", capitulos: 6  },
  { nome: "Filipenses",       abrev: "fp",   testamento: "NT", capitulos: 4  },
  { nome: "Colossenses",      abrev: "cl",   testamento: "NT", capitulos: 4  },
  { nome: "1 Tessalonicenses",abrev: "1ts",  testamento: "NT", capitulos: 5  },
  { nome: "2 Tessalonicenses",abrev: "2ts",  testamento: "NT", capitulos: 3  },
  { nome: "1 Timóteo",        abrev: "1tm",  testamento: "NT", capitulos: 6  },
  { nome: "2 Timóteo",        abrev: "2tm",  testamento: "NT", capitulos: 4  },
  { nome: "Tito",             abrev: "tt",   testamento: "NT", capitulos: 3  },
  { nome: "Filemom",          abrev: "fm",   testamento: "NT", capitulos: 1  },
  { nome: "Hebreus",          abrev: "hb",   testamento: "NT", capitulos: 13 },
  { nome: "Tiago",            abrev: "tg",   testamento: "NT", capitulos: 5  },
  { nome: "1 Pedro",          abrev: "1pe",  testamento: "NT", capitulos: 5  },
  { nome: "2 Pedro",          abrev: "2pe",  testamento: "NT", capitulos: 3  },
  { nome: "1 João",           abrev: "1jo",  testamento: "NT", capitulos: 5  },
  { nome: "2 João",           abrev: "2jo",  testamento: "NT", capitulos: 1  },
  { nome: "3 João",           abrev: "3jo",  testamento: "NT", capitulos: 1  },
  { nome: "Judas",            abrev: "jd",   testamento: "NT", capitulos: 1  },
  { nome: "Apocalipse",       abrev: "ap",   testamento: "NT", capitulos: 22 },
];

export const LIVROS_AT = LIVROS_BIBLIA.filter(l => l.testamento === "AT");
export const LIVROS_NT = LIVROS_BIBLIA.filter(l => l.testamento === "NT");
